DOMAIN_NAME: codo.actanble.org
LOCALHOST_IP: 192.168.2.228

# Db Host setting
## 支持异地数据库启动
MYSQL_HOST: 192.168.2.228
REDIS_HOST: 192.168.2.228
MQ_HOST: 192.168.2.228

# Mysql settings
MYSQL_PASSWORD: m9uSFL7duAVXfeAwGUSG
MYSQL_ROOT_PASSWORD: m9uSFL7duAVXfeAwGUSG
MYSQL_ROOT_USER: root
MYSQL_SERVER_PORT: 3306
#MYSQL_SERVER_DB: codo
REDIS_PASSWORD: cWCVKJ7ZHUK12mVbivUf
REDIS_PORT: 6379
MQ_USER: ss
MQ_PASSWORD: 5Q2ajBHRT2lFJjnvaU0g

# web token settings
cookie_secret: nJ2oZis0V/xlArY2rzpIE6ioC9/KlqR2fd59sD=UXZJ=3OeROB
token_secret: pXFb4i%*834gfdh963df713iodGq4dsafsdadg7yI6ImF1999aaG7

# Mysqldb settings
#DEFAULT_DB_DBHOST: 192.169.2.228
#DEFAULT_DB_DBPORT: 3306
#DEFAULT_DB_DBUSER: root
#DEFAULT_DB_DBPWD: m9uSFL7duAVXfeAwGUSG
#DEFAULT_DB_DBNAME: codo
#READONLY_DB_DBHOST: 192.169.2.228
#READONLY_DB_DBPORT: 3306
#READONLY_DB_DBUSER: root
#READONLY_DB_DBPWD: m9uSFL7duAVXfeAwGUSG
#READONLY_DB_DBNAME: codo

# RabbitMq settings
#DEFAULT_MQ_ADDR: 192.169.2.228
#DEFAULT_MQ_USER: ss
#RABBITMQ_DEFAULT_USER: ss
#RABBITMQ_DEFAULT_PASS: 5Q2ajBHRT2lFJjnvaU0g
#DEFAULT_MQ_PWD: 5Q2ajBHRT2lFJjnvaU0g

## Redis settings
#DEFAULT_REDIS_HOST: 192.169.2.228
#DEFAULT_REDIS_PORT: 6379
#DEFAULT_REDIS_PASSWORD: cWCVKJ7ZHUK12mVbivUf
